sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
      - xvfb
  jwt:
    secure: m2tGx8Pc2ZuukNqWxcDBZsuLT1xWYDz3ZJ1MG8+69EZwjjHT07SUPX8hoHt6Xa2tWGJiv0yHB5BdDlzFSYr104tNwPpUOaUPosDTSeL0M5gbsSX5+0orILeltCi7UJKIiJZ9kNAfq9bTIMdYb3mRm86nJp8lUd3Ok52u9digS98=
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
branches:
  only:
  - 0.8
  - dev
script:
- npm run build:ci
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run release:ci; fi
env:
  global:
  - GH_REF: github.com/ractivejs/ractive.git
  - CDN_REF: github.com/ractivejs/cdn.ractivejs.org.git
  - SAUCE_USERNAME: ractive
  - secure: nlnXJW/imf/w6qdTd7UCpRqLhLioxU6fllJPbP1DZr/9rp44HNVSPNxxGrA808VDXQ1ccpXBxIV9mgIi4Q/G0FUILA5NsSGYdQE00A+Lw3qnvv5FQ7Qoux44BKYi4L1W+4Zi3NEr7TAL+/dHCAk5k/ZKLTCCxiziAEw3M+akE4A=
  - secure: W+gKWvHDgHXI+1tARD+QxFbgjxhU6AN9Fn40v4u5lNwjOXuxcgH6UMK9YaePPaFAO62H7EeUZdbeghn3qTixR6naUewdq+U50U814Y6gcXhAAHcPoHBkbUOUAuUWbp3saNcECOMUlLsiOl2S+A8iMvwEFqz84O2Pdwj68TmKJHw=
  - secure: iUqcSoWpThxocqJsoJAhbEZeQWibsM1V6PsQN9dGOS2DhaEcPaKg8yz7wL1V+rNKLzBPo9p41BPT6ij8SeVVMJ8lsvjJgptPItoPjeS9CQ9vzQ/aC/I+56mD86I7aMwkFciZXWVYYRPZ9u/5qaqUcsKyn6LVz41CZfFiJXCbm64=
